version: '2.3'

services:
  main:
    container_name: "retrieval_extractor_resnet50_rmac"
    build:
      context: ./
      dockerfile: Dockerfile
    runtime: nvidia
    restart: always
    env_file:
      - "docker-compose-env/main.env"
      - "docker-compose-env/db.env"
    expose:
      - "8000"
    ports:
      - "38010:8000"
    ipc: host
    stdin_open: true
    tty: true
    depends_on:
      extractor_db:
        condition: service_healthy
    links:
      - extractor_db

  extractor_db:
    container_name: "retrieval_extractor_resnet50_rmac_db"
    image: mysql:8.0.21
    restart: always
    env_file:
      - docker-compose-env/db.env
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


